[package]
name = "plot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]


[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
nalgebra = "0.33" 
serde = { version = "1.0", features = ["derive"] }
web-sys = {version = "0.3", features = [ "console" ]}